location               = "West Europe"
org_name               = "cf"
project_name           = "sei"
resource_group_name    = "rg"
storage_account_name   = "sa"
storage_account_name_2 = "sa_2"
storage_account_prefix = "sa"